---
- name: Update apt cache for MySQL
  apt:
    update_cache: yes

- name: Install MySQL server
  apt:
    name: mysql-server
    state: present

- name: Install Python MySQL library
  apt:
    name: python3-mysqldb
    state: present

- name: Ensure MySQL service is started and enabled
  service:
    name: mysql
    state: started
    enabled: yes

- name: Create WordPress database
  mysql_db:
    name: "{{ wp_db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress and grant privileges
  mysql_user:
    name: "{{ wp_db_user }}"
    password: "{{ wp_db_password }}"
    priv: "{{ wp_db_name }}.*:ALL"
    host: "localhost"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
